---
- name: Playbook for creating 
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - ec2_asg:
        name: special
        load_balancers: [ 'lb1', 'lb2' ]
        availability_zones: [ 'eu-central-1a', 'eu-central-1b' ]
        launch_config_name: 'lc-1'
        min_size: 3
        max_size: 12
        desired_capacity: 5
        vpc_zone_identifier: [ 'subnet-0565bd985d18ad5d2', 'subnet-033c42a29ee427e69' ]
        tags:
          - environment: production
            propagate_at_launch: yes
    - name: create launch config
     ec2_lc:
       name: my_new_lc
       image_id: ami-04cf43aca3e6f3de3
       key_name: ansible
       region: eu-central-1
       security_groups: sg-8ae259e8
       instance_type: t2.micro
       assign_public_ip: yes
       instance_port: 80         
- local_action:
    module: ec2_elb_lb
    name: new-vpc
    scheme: internal
    state: present
    instance_ids:
      - i-0603275ab04222954
    purge_instance_ids: true
    subnets:
      - subnet-0565bd985d18ad5d2
      - subnet-033c42a29ee427e69
    listeners:
      - protocol: http # options are http, https, ssl, tcp
        load_balancer_port: 80
  
        
   
