---
- name: Playbook for tasks
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Download wordpress
      get_url:
        url:"https://wordpress.org/latest.zip"
        dest: /tmp/  