---
- name: Test Playbook
  hosts: all
  become: true
  become_method: sudo
  connection: ssh
  ignore_errors: false
  tasks:
    - name: Task Name Here
      ping:
shell: "find   /    -type f    -name  *.lo     -mtime +90    -exec gzip -v9 {} \;"      