---
- name: Playbook for sec grou
  hosts: localhost
  tasks:
    - name: Create Sec Group1
      ec2_group:
        name: SecGroup
        description: sg with rule descriptions
        vpc_id: vpc-79226b03
        region: us-east-1
        rules:
          - proto: tcp
            ports:
            - 80 
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            ports:
            - 22
            cidr_ip: 0.0.0.0/0    
       