---
- name: Creates subnets
  hosts: localhost
  gather_facts: yes
#  vars_files: subnet_vars
  tasks:
    - name: create subnet a
      ec2_vpc_subnet:
        state: present
        region: us-east-1 
        vpc_id: vpc-0b97f5aca02dc7cb4
        cidr: 172.32.0.0/32
#        az: "{{az}}"
#        resource_tags:
#          Name: Db_Subnet1 
#      register: db_subnet
#  - name: create subnet b
#    ec2_vpc_subnet:
#      state: present
#      region: "{{region}}"
#      vpc_id: "{{vpc.id}}"
#      cidr: "{{cidr}}"
#      az: "{{az}}"
#        resource_tags:
#          Name: Db_Subnet2 
#      register: db_subnet
#  - name: create subnet c
#    ec2_vpc_subnet:
#      state: present
#      region: "{{region}}"
#      vpc_id: "{{vpc.id}}"
#      cidr: "{{cidr}}"
#      az: "{{az}}"
#        resource_tags:
#          Name: Db_Subnet3 
#      register: db_subne
