---
- name: Playbook for Provisioning
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: create vpc in region
      ec2_vpc_net:
        name: new-vpc
        cidr_block: 10.10.0.0/16
        region: eu-central-1
        tags:
          module: ec2_vpc_net
          task: vpc
      register: vpc_info

    - name: Create subnet for database servers
      ec2_vpc_subnet:
        state: present
        region: eu-central-1
        az: eu-central-1a
        vpc_id:  "{{vpc_info_info.vpcs[0].vpc_id}}"
        cidr: 10.10.1.0/24
        resource_tags:
          Name: Private Subnet
      register: private_subnet
     - name: Create subnet for database servers
      ec2_vpc_subnet:
        state: present
        region: eu-central-1
        az: eu-central-1a
        vpc_id:  "{{vpc_info_info.vpcs[0].vpc_id}}"
        cidr: 10.10.2.0/24
        resource_tags:
          Name: Private Subnet
      register: private_subnet 
     - name: Create subnet for database servers
      ec2_vpc_subnet:
        state: present
        region: eu-central-1
        az: eu-central-1a
        vpc_id:  "{{vpc_info_info.vpcs[0].vpc_id}}"
        cidr: 10.10.1.0/24
        resource_tags:
          Name: Private Subnet
      register: private_subnet 
      
    - name: Create subnet for  web servers
      ec2_vpc_subnet:
        state: present
        region: eu-central-1
        az: eu-central-1b
        vpc_id:  "{{vpc_info_info.vpcs[0].vpc_id}}"
        cidr: 10.10.101.0/24
        resource_tags:
          Name: Public Subnet
      register: public_subnet 
      - name: Create subnet for web servers
       ec2_vpc_subnet:
         state: present
         region: eu-central-1
         az: eu-central-1b
         vpc_id:  "{{vpc_info_info.vpcs[0].vpc_id}}"
         cidr: 10.10.102.0/24
         resource_tags:
          Name: Public Subnet
      register: public_subnet  
    
     - name: Create subnet for web servers
      ec2_vpc_subnet:
        state: present
        region: eu-central-1
        az: eu-central-1b
        vpc_id:  "{{vpc_info_info.vpcs[0].vpc_id}}"
        cidr: 10.10.103.0/24
        resource_tags:
          Name: Public Subnet
      register: public_subnet  
      
    - name: example using security group rule descriptions
      ec2_group:
        name: ssh and httpd open
        description: sg with rule descriptions
        vpc_id: "{{vpc_info_info.vpcs[0].vpc_id}}"0 
        region: eu-central-1
        rules:
          - proto: tcp
            ports:
              - 80
              - 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 80
