---
- name: Playbook for Route table
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Set up public subnet route table
      ec2_vpc_route_table:
        vpc_id: vpc-03397932ec4cfdbce
        region: us-east-1
        tags:
          Name: Public
        subnets:
          - subnet-039905d2e3ce5ff86
          - subnet-024b5de3703b90a20
          - subnet-079e59b1170756708
        routes:
          - dest: 0.0.0.0/0
            gateway_id: igw-02b1c2836b61d22e9
      register: public_route_table