---
- name: Playbook for Route table for  Private
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Set up private subnet route table
      ec2_vpc_route_table:
        vpc_id: vpc-0175952c440722623
        region: us-east-1
        tags:
          Name: private
        subnets:
          - subnet-00420af39121a1c1a
          - subnet-08c548653b465fd75
          - subnet-0e1c442d3c9429490
        routes:
          - dest: 10.0.0.0/16
      register: private_route_table