---
- name: Playbook for sec groups
  hosts: localhost
  tasks:

    - name: collect VPC info
      ec2_vpc_net_facts:
        region: us-east-1
        filters:
          "tag:Name": VPC
      register: VPC1 


    


    - name: Create Sec Group1
      ec2_group:
        name: SecGroupFprVPC
        description: sg with 1
        vpc_id: "{{VPC.vpcs[0].vpc_id}}"
        region: us-east-1
        rules:
          - proto: tcp
            ports:
            - 80 
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            ports:
            - 22
            cidr_ip: 0.0.0.0/0    
       