---
- name: Playbook for sec groups
  hosts: localhost
  tasks:
    - name: VPC for class
      ec2_vpc_net:
        name: TaskVPC
        cidr_block: 10.10.0.0/16
        region: us-east-1
      tags:
        task: VPC
        class: ansible
    