---
- name: Playbook for sec groups
  hosts: localhost
  tasks:
    - name: Create Sec Group1
      ec2_group:
        name: SecGroupFprVPC
        description: sg with 1
        vpc_id: vpc-0175952c440722623
        region: us-east-1
        rules:
          - proto: tcp
            ports:
            - 80 
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            ports:
            - 22
            cidr_ip: 0.0.0.0/0    
       