---
- name: Playbook for VPC
  hosts: localhost
  tasks:
    - name: Create subnet for database servers
      ec2_vpc_subnet:
    state: present
    vpc_id: vpc-123456
    cidr: 10.0.1.16/28
    resource_tags:
      Name: Database Subnet
  register: database_subnet